knu/urls.py
from django.urls import path
from . import views
from knu.dash_apps.finished_apps import simpleexample
from knu.dash_apps.finished_apps import location

app_name = 'knu'
urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.index, name='index'),
    path('<int:value_id>/value/', views.value, name='value'),
    path('location', views.location, name='location'),
    path('<int:scenario_id>/scenario/', views.scenario, name='scenario'),
    path('<int:eval_id>/eval/', views.eval, name='eval'),
]

knuproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.views.generic import TemplateView

from knu.dash_apps.finished_apps import plotly_apps    # pylint: disable=unused-import
from knu.dash_apps.finished_apps import dash_apps      # pylint: disable=unused-import
from knu.dash_apps.finished_apps import bootstrap_app  # pylint: disable=unused-import

from django_plotly_dash.views import add_to_session
from knu import views


urlpatterns = [
    path('knu/', include('knu.urls')),
    path('', include('knu.urls')),
    path('member/', include('django.contrib.auth.urls')),
    path('member/', include('member.urls')),
    path('admin/', admin.site.urls),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),

]

member/urls.py
from django.urls import path
from . import views


app_name = 'member'
urlpatterns = [
    path('login_user', views.login_user, name='login'),
    path('logout_user', views.logout_user, name='logout'),
]

knu/models.py
from django.db import models

# Create your models here.


class Area(models.Model):
    area_text = models.CharField(max_length=20)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.area_text

class Keyfigure(models.Model):
    description = models.CharField(max_length=200)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    class Meta:
        abstract = True


class Fact(Keyfigure):
    fact_text = models.CharField(max_length=40)

    def __str__(self):
        return self.area.area_text + '--' + self.fact_text

class Task(models.Model):
    task_text = models.CharField(max_length=40)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.task_text

class Calculation(Keyfigure):
    calculation_text = models.CharField(max_length=40)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    def __str__(self):
        return self.area.area_text + '--' + self.calculation_text

class Dimension(models.Model):
    dimension_text = models.CharField(max_length=20)

    def __str__(self):
        return self.dimension_text


class Unit(models.Model):
    unit_text = models.CharField(max_length=5)

    def __str__(self):
        return self.unit_text

class Number(models.Model):
    fact = models.ForeignKey(Fact, on_delete=models.CASCADE)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    value = models.CharField(max_length=20)
    class Meta:
        abstract = True


class Value(Number):
    source = models.CharField(max_length=200, default='')

    def __str__(self):
        return self.fact.fact_text + ' (' + self.source + ')'

class Result(Number):
    method = models.CharField(max_length=200, default='')

    def __str__(self):
        return self.fact.fact_text + ' (' + self.method + ')'

class Select(models.Model):
    select_txt = models.CharField(max_length=20)
    value = models.ForeignKey(Value, on_delete=models.CASCADE)
    dimension = models.ForeignKey(Dimension, on_delete=models.CASCADE)

    def __str__(self):
        return self.dimension.dimension_text + ' = ' + self.select_txt

class SelectResult(models.Model):
    select_txt = models.CharField(max_length=20)
    result = models.ForeignKey(Result, on_delete=models.CASCADE)
    dimension = models.ForeignKey(Dimension, on_delete=models.CASCADE)

    def __str__(self):
        return self.dimension.dimension_text + ' = ' + self.select_txt

class Scenario(models.Model):
    scenario_text = models.CharField(max_length=40)
    description = models.CharField(max_length=200)
    inheritance = models.ManyToManyField('self', related_name='mothers', symmetrical=False)
    prio = models.CharField(max_length=1, default = 'C')
    def __str__(self):
        return self.scenario_text


class Impact(models.Model):
    scenario = models.ForeignKey(Scenario, on_delete=models.CASCADE, related_name='impacts')
    impact_text = models.CharField(max_length=20)
    description = models.CharField(max_length=200)
    value = models.ForeignKey(Value, on_delete=models.CASCADE, blank=True, null=True)
    def __str__(self):
        return self.impact_text


class Eval(models.Model):
    eval_text = models.CharField(max_length=40)
    description = models.CharField(max_length=200)
    scenario = models.ForeignKey(Scenario, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)

    def __str__(self):
        return self.eval_text

class SelectEval(models.Model):
    select_txt = models.CharField(max_length=20)
    eval = models.ForeignKey(Eval, on_delete=models.CASCADE)
    dimension = models.ForeignKey(Dimension, on_delete=models.CASCADE)
    def __str__(self):
        return self.dimension.dimension_text + ' = ' + self.select_txt

member/models.py
from django.db import models

# Create your models here.

knu/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from .models import Value, Scenario, Eval
from plotly.offline import plot
import plotly.graph_objects as go


def home(request):
    value_list = Value.objects.order_by('-source')[:5]
    context = {
        'value_list': value_list,
    }
    return render(request, 'knu/home.html', context)


def value(request, value_id):
    valueobject = get_object_or_404(Value, pk=value_id)
    context = {
        'value': valueobject,
    }
    return render(request, 'knu/detail.html', {'value': valueobject})


def index(request):
    value_list = Value.objects.order_by('-source')
    context = {
        'value_list': value_list,
    }
    return render(request, 'knu/index.html', context)


def location(request):
    value_list = Value.objects.order_by('-source')[:5]
    context = {
        'value_list': value_list,
    }
    return render(request, 'knu/location.html', context)


def scenario(request, scenario_id):
    scenarioobject = get_object_or_404(Scenario, pk=scenario_id)
    context = {
        'scenario': scenarioobject,
    }
    return render(request, 'knu/scenario.html', {'scenario': scenarioobject})


def eval(request, eval_id):
    evalobject = get_object_or_404(Eval, pk=eval_id)
    context = {
        'eval': evalobject,
    }
    return render(request, 'knu/eval.html', {'eval': evalobject})

member/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            return redirect('knu:home')
        else:
            messages.success(request, ("Du konntest nicht angemeldet werden"))
            return redirect('member:login')
    else:
        pass

    # Return an 'invalid login' error message.


        return render(request, 'authenticate/login.html', {})

def logout_user(request):
    logout(request)
    messages.success(request, ("Du bist abgemeldet"))
    return redirect('knu:home')
# Create your views here.

member/templates/authenticate/login.html
{%  extends 'base.html' %}
{% load static %}
{% load admin_urls %}
{% block content %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Anmeldung</h1>
    </div>

    </form>

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Willkommen zurück!</h1>
                                    </div>
                                    <form action = "" method="POST">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <input type="text" class="form-control form-control-user"
                                                name="username" aria-describedby="emailHelp"
                                                placeholder="Benutzernamen eingeben...">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                name="password" placeholder="Passwort">
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox small">
                                                <input type="checkbox" class="custom-control-input" id="customCheck">
                                                <label class="custom-control-label" for="customCheck">Angemeldet bleiben</label>
                                            </div>
                                        </div>
                                            <input type = "submit" value="Anmelden" class="btn btn-secondary">
                                        <hr>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="forgot-password.html">Passwort vergessen?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="register.html">Benutzer beantragen!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>




{% endblock %}

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>KNU</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>


</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    {% include 'partials/_sidebar.html' %}
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
{% include 'partials/_topbar.html' %}
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">
            {% if messages %}
                <div class="col-lg-6 mb-4">
                     <div class="card bg-danger text-white shadow">
                        <div class="card-body">

                                {% for message in messages %}
                                     {{ message }}
                                {% endfor %}

                        </div>
                     </div>
                </div>
            {% endif %}



            {% block content %}

            {% endblock %}
       </div>


      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      {% include 'partials/_footer.html' %}
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Abmelden?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Wähle "Abmelden" unten falls Du die aktuelle Sitzung beenden möchtest.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Abbrechen</button>
          <a class="btn btn-primary" href={% url 'member:logout' %}>Abmelden</a>
        </div>
      </div>
    </div>
  </div>
  </div>
  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

  <!-- Page level plugins -->
  <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

  <!-- Page level custom scripts -->
  <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
  <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>

</body>

</html>

templates/knu/Copy.html
{%  extends 'base.html' %}
{% load static %}
{% block content %}
    {% load plotly_dash %}
<h1>Home Page</h1>

   <!-- Area Chart -->
<div class="col-xl-8 col-lg-7">
    <div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
        <div
            class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">CO2 Ausstoss</h6>
            <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                 aria-labelledby="dropdownMenuLink">
                 <div class="dropdown-header">Dropdown Header:</div>
                      <a class="dropdown-item" href="#">Action</a>
                      <a class="dropdown-item" href="#">Another action</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">Something else here</a>
                </div>
               </div>
            </div>
            <!-- Card Body -->
            <div class="card-body">Übersicht 2022 - 2035</div>

                                    <div class="{% plotly_class name='SimpleExample' %} card" style="height: 100%; width: 100%">
            {% plotly_app name='SimpleExample' ratio=0.75 %}


            </div>
        </div>
    </div>
</div>





    <!-- Area Chart -->
<div class="col-xl-8 col-lg-7">
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div
            class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Neuste Fakten</h6>
            <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                    aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Dropdown Header:</div>
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </div>
        </div>
        <!-- Card Body -->
          {% if value_list %}
            <ul>
            {% for value in value_list %}
                <li>{{ value.fact }} = <a href="/knu/{{ value.id }}/">{{ value.value }}</a> {{ value.unit }}</li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No values are available.</p>
        {% endif %}


        </div>
    </div>
</div>
{% endblock %}

templates/knu/detail.html
{%  extends 'base.html' %}
{% load static %}
{% load admin_urls %}
{% block content %}
<h1>Einzelwert</h1>
 {% if value %}
    <ul>
        <li>Quelle: {{ value.source }}</li>
        <li>Fakt: {{ value.fact }}</li>
        <li>Wert: {{ value.value }}</li>
        <li>Einheit: {{ value.unit }}</li>
        <li><a href={% url 'admin:knu_value_change' value.id %}>Ändern</a></li>
    </ul>
{% else %}
    <p>Kein Wert verfügbar.</p>
{% endif %}



{% endblock %}

templates/knu/eval.html
{%  extends 'base.html' %}
{% load static %}
{% load admin_urls %}
{% block content %}
 {% if eval %}
    <h1>Berechnung</h1>
    <ul>
        Berechnung: <a href={% url 'admin:knu_eval_change' eval.id %}>{{ eval.eval_text }}</a><br>
        Beschreibung: {{ eval.description }}<br><br>
        Aufgabe: {{ eval.task.task_text }}<br>
        Szenario: <a href={% url 'admin:knu_scenario_change' eval.scenario.id %}>{{ eval.scenario.scenario_text }}</a><br>

    </ul>
 {% else %}
    <p>Fehler: Keine Berechnung verfügbar.</p>
{% endif %}



{% endblock %}

templates/knu/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% load plotly_dash %}
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">K.N.U.</h1>
        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
    </div>

    <div class="row">
        <!-- Area Chart -->
        <div class="col-xl-12 col-lg-12">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Kontext</h6>
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                             aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-header">Dropdown Header:</div>
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div>
                </div>
                <!-- Card Body -->

                <div class="{% plotly_class name='Location' %} card" style="height: 100%; width: 100%">
                    {% plotly_app name='Location' ratio=0.6 %}
                </div>
            </div>
        </div>
    </div>
    <div class="row">

        <!-- Area Chart -->
        <div class="col-xl-12 col-lg-12">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">CO2 Ausstoss</h6>
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                             aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-header">Dropdown Header:</div>
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">Übersicht 2022 - 2035</div>

                <div class="{% plotly_class name='SimpleExample' %} card" style="height: 100%; width: 100%">
                    {% plotly_app name='SimpleExample' ratio=0.75 %}
                </div>
            </div>
        </div>
    </div>


    <!-- Card Body -->
    {% if value_list %}
        <ul>
            {% for value in value_list %}
                <li>{{ value.fact }} = <a href={% url 'knu:value' value_id=value.id %}>{{ value.value }}</a> {{ value.unit }}</li>

            {% endfor %}
            {% if value_list|length == 5 %}
                <li><a href={% url 'knu:index' %}>...</a></li>
            {% endif %}
        </ul>
    {% else %}
        <p>No values are available.</p>
    {% endif %}


{% endblock %}

templates/knu/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% load plotly_dash %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Fakten</h1>
        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
    </div>
    <!-- Area Chart -->
    <div class="col-xl-12 col-lg-7">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Neuste Fakten</h6>
                <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                         aria-labelledby="dropdownMenuLink">
                        <div class="dropdown-header">Dropdown Header:</div>
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </div>
            </div>
            <!-- Card Body -->
            {% if value_list %}
                <ul>
                    {% for value in value_list %}
                        <li>{{ value.fact }} = <a href={% url 'knu:value' value_id=value.id %}>{{ value.value }}</a> {{ value.unit }}</li>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>No values are available.</p>
            {% endif %}


        </div>
    </div>
{% endblock %}

templates/partials/_sidebar.html
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href={% url 'knu:home' %}>
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-calculator"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Klimaneutrales Ubstadt-Weiher</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href={% url 'knu:home' %}>
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Interface
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-cog"></i>
          <span>Modell</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">KNU Berechnungen:</h6>
               {% for e in evals %}
                     <a class="collapse-item" href={% url 'knu:eval' eval_id=e.id %}>{{ e.eval_text }}</a>
               {% endfor %}
          </div>
        </div>
      </li>

      <!-- Nav Item - Utilities Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-fw fa-wrench"></i>
          <span>Was wäre wenn</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Szenario:</h6>
                  {% for sc in main_scenarios %}
                     <a class="collapse-item" href={% url 'knu:scenario' scenario_id=sc.id %}>{{ sc.scenario_text }}</a>
                  {% endfor %}
            <a class="collapse-item" href="utilities-other.html">Weitere...</a>
          </div>
        </div>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Addons
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
          <i class="fas fa-fw fa-folder"></i>
          <span>Seiten</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Hilfseiten:</h6>
            <a class="collapse-item" href={% url 'member:login' %}>Anmelden</a>
            <a class="collapse-item" href="register.html">TODO Registrieren</a>
            <a class="collapse-item" href="forgot-password.html">TODO Passwort vergessen</a>
            <a class="collapse-item" href={% url 'admin:login' %}>Adminportal inkl Datenpflege</a>
            <div class="collapse-divider"></div>
            <h6 class="collapse-header">Sonstiges:</h6>
            <a class="collapse-item" href="404.html">TODO 404 Page</a>
          </div>
        </div>
      </li>

      <!-- Nav Item - Charts -->
      <li class="nav-item">
        <a class="nav-link" href={% url 'knu:index' %}>
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Grafiken</span></a>
      </li>

      <!-- Nav Item - Tables -->

      <li class="nav-item">
        <a class="nav-link" href={% url 'admin:login' %}>
          <i class="fas fa-fw fa-table"></i>
          <span>Daten1</span></a>
      </li>
      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>